### PR TITLE
A level Order Traversal Of A Binary Tree

### PR DESCRIPTION
**Pull request by AkoredeAjibola**
A level Order Traversal Of A Binary Tree

### CODE REVIEW

**Comment by AkoredeAjibola** [comment]
Full name: Ajibola Akorede Opemipo 
GitHub name: AkoredeAjibola 
Email: ajibolaakorede2021@gmail.com

**Review by AkoredeAjibola — COMMENTED** [review]
Name: Ajibola Akorede Opemipo 
GitHub: AkoredeAjibola 
Email: ajibolaakorede2021@gmail.com

**Comment by AkoredeAjibola** [comment]
A level Order Traversal Of A Binary Tree
Name: Ajibola Akorede Opemipo
Github: AkoredeAjibola
email: ajibolaakorede2021@gmail.com

**Comment by K-Honsu** [comment]
good

**Review by markdave123-py — COMMENTED** [review]
update your assignments so you wont be evicted.
do this before 2pm tomorrow

**Pull request closed without merging**
